gtushell:
	gcc -c  -std=gnu99 main.c -Wall
	gcc -o gtushell main.o
	gcc -c  -std=gnu99 pwd.c -Wall
	gcc -o pwd pwd.o
	gcc -c  -std=gnu99 bunedu.c -Wall
	gcc -o bunedu bunedu.o
	gcc -c  -std=gnu99 wc.c -Wall
	gcc -o wc wc.o
	gcc -c  -std=gnu99 cat.c -Wall
	gcc -o cat cat.o
	gcc -c  -std=gnu99 lsf.c -Wall
	gcc -o lsf lsf.o

clean:
	rm -f *.o gtushell
	rm -f *.o pwd
	rm -f *.o bunedu
	rm -f *.o wc
	rm -f *.o cat
	rm -f *.o lsf
